server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:TTODS/cloud2020-config.git
          search-paths: cloud2020-config
          password: xuwenbin2019
          username: ttods
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka
